### ISSUE TITLE
REQ UPDATE - update blogtruyenmoi

### ISSUE THREAD

**Issue by quaanpa** [AlanNois/TruyenViet-0.8#11]
blogtruyen - https://blogtruyenmoi.com/
DES:
Nhờ bác update lại hoặc thêm source blogtruyenmoi. 1 số truyện bên blogtruyen.vn nó không update nữa với nhiều truyện team dịch cũng chỉ đăng ở mỗi blogtruyenmoi.com
Em cảm ơn bác ạ

**Comment by AlanNois** [comment]
?

**Comment by quaanpa** [comment]
> ?

Em mới update lại req ạ

**Comment by AlanNois** [comment]
Mình upd cho cả bản 0.8 với dev về domain ext Blogtruyen lâu rồi mà? Liệu bạn đã upd lại ext trong Paperback chưa ạ?

**Comment by AlanNois** [comment]
Vui lòng kiểm tra và phản hồi lại để mình có thể xử lý vấn đề. Nếu sau 48h bạn không còn phản hồi gì với issue này mình sẽ đóng lại

**Comment by quaanpa** [comment]
À oke bác done rồi ạ
Này do lỗi mạng bên máy em
Cảm ơn bác nhiều ạ
E xin phép close issue ạ
